apiVersion: v1
kind: Service
metadata:
  name: aks-service 
  labels:
    app: aks-helloworld
spec:
  type: ClusterIP
  selector:
    app: aks-helloworld
  ports:
  - name: http
    port: 80
    targetPort: 8080
